[features]
seeds = false
skip-lint = false
[programs.localnet]
solanapdas = "EYahPbK4gjtQNwdigmwSvoPQvPiwSQNo3KrScmc2RqBH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mike/.config/solana/dev-phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
